CREATE TABLE IF NOT EXISTS admin(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	line VARCHAR(100) NOT NULL,
	picture VARCHAR(100) NULL,
	password VARCHAR(100) NOT NULL,
	recovery VARCHAR(100) NOT NULL,
	join_date TIMESTAMP	
)

CREATE TABLE IF NOT EXISTS company(
   id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
   title VARCHAR(100) NOT NULL UNIQUE,
   name VARCHAR(100) NOT NULL,
   phone VARCHAR(100) NOT NULL UNIQUE,
   location VARCHAR(100) NOT NULL,
   status varchar(3) NOT NULL,
   picture VARCHAR(100) NULL
)
