CREATE TABLE IF NOT EXISTS category(
	id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	product_id INT UNSIGNED NULL,
	technology VARCHAR(100) NULL,
	household VARCHAR(100) NULL,
	foodies VARCHAR(100) NULL,
	wear VARCHAR(100) NULL,
	add_date TIMESTAMP
	
)

